apiVersion: v1
kind: PersistentVolume
metadata:
  name: tram-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: <your-ebs-volume-id>
    fsType: ext4
